import './globals.css';
//import { Inter } from 'next/font/google'
//const inter = Inter({ subsets: ['latin'] })
import localFont from 'next/font/local';
import Header from './components/Header';
import Footer from './components/Footer';
import WhatsAppButton from './components/WhatsAppButton';

const museo = localFont({
  src: '../public/fonts/Museo.ttf',
  variable: '--font-museo',
});

const tusker = localFont({
  src: '../public/fonts/Tusker.ttf',
  variable: '--font-tusker',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${museo.variable}  ${tusker.variable}`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
